### ISSUE TITLE
[Documentation] Pocketbase not reachable

### ISSUE THREAD

**Issue by starredev** [MRSessions/pocketbase-vue-starter#10]
Great repo, thanks for that!

When I try to load pocketbase UI it redirects me to https://localhost:8090 (VUETIFY PROJECT).

pocketbase-vue-starter  | Initial Admin Already Setup
pocketbase-vue-starter  | 2023/02/21 13:33:54 Server started at http://0.0.0.0:8090
pocketbase-vue-starter  |  ➜ REST API: http://0.0.0.0:8090/api/
pocketbase-vue-starter  |  ➜ Admin UI: http://0.0.0.0:8090/_/

Any solution?

**Comment by MRSessions** [comment]
Hey @raizdev,

Thanks for reaching out on it. I know I don't have it documented well at the moment as of working on it last night. 

Basically, since the app is being served via PocketBase, I wanted to block access to the PocketBase UI. It is still available though, you have to add a little extra to the end of the string (`/_/?#/login`) (`http://localhost:8090/_/?#/login`)

The end goal is to rewrite everything through `/_` to the Vue front end, so that no one can see anything related to PocketBase.

If you do not want this, it can be changed in the pocketbase.go file in the section below. You can remove the app.DB check and the if/else statement as well as all the print lines.
```go
app.OnBeforeServe().Add(func(e *core.ServeEvent) error {
  var total int
  err := app.DB().
	  Select("count(*)").
	  From("_admins").
	  Row(&total)
  if err != nil {
	  return err
  }
  if total > 0 {
	  e.Router.Pre(middleware.Rewrite(map[string]string{
		  "/_":  "/",
		  "/_/": "/",
	  }))
	  println("Initial Admin Already Setup")
  } else {
	  e.Router.Pre(middleware.Rewrite(map[string]string{
		  "/_":  "/",
		  "/_*": "/",
	  }))
	  println()
	  println("Initial Admin Setup Needed")
	  println()
	  println("PocketBase Admin Setup page ('/_/?installer#/') is replaced by the vue-client SetupAdmin page")
	  println()
	  println("After admin setup, you'll need to restart the container to access the PocketBase UI")
	  println()
  }
  e.Router.GET("/*", apis.StaticDirectoryHandler(os.DirFS(publicDir), indexFallback))
  return nil
  })
```

I will try to get some documentation for this updated this afternoon/evening.

Thank you,
@MRSessions 

Also, keep an eye out, I am still working on adding things in.

**Comment by MRSessions** [comment]
Actually @raizdev, I have decided to try and work with an environment variable `POCKETBASE_DISABLE_UI` to enable or disable the routes completely instead of trying to do all that nonsense in my previous comment. This will still allow the `/api` route.

The default value will be `false` to enable the routes for development purposes and won't need to be set. Only if you want to disable them will you need to set `POCKETBASE_DISABLE_UI=true`.

```go
var diablePocketbaseUI = os.Getenv("POCKETBASE_DISABLE_UI") == "false"

if diablePocketbaseUI {
  e.Router.Pre(middleware.Rewrite(map[string]string{
    "/_":  "/",
    "/_*": "/",
  }))
  log.Default().Println("PocketBase UI is disabled")
}
```

This is my first time working in Go, so I may need to play around and test it well. This should make it easy with Docker Compose.

Additional Update: I've been working on the documentation (should hopefully have the new version up tonight), and when I came to that section, that's what gave me the better idea of an environment variable.

**Comment by MRSessions** [comment]
Alright @raizdev last update on this.

Here are the changes that I made to this. I'm about to make a PR on develop (Having some people review the README.md).

See below for changes regarding this, hopefully this will make it easier instead of what I had before. This is all documented in the README.md now.

Once this issue is close, the changes will be in the develop branch. You can pull that down and see the changes.

I have setup PocketBase to remove(rewrite) the PocketBase default routes. By default, it is allowed. If you want to disable PocketBase routes, you can set the environment variable `POCKETBASE_DISABLE_UI` to `true`. This will keep users from accessing the PocketBase UI. Find details in below code sections.

<details>
  <summary>pocketbase.go</summary>

  ```go
  func main() {
    app.OnBeforeServe().Add(func(e *core.ServeEvent) error {
      if getenvBool("POCKETBASE_DISABLE_UI") {
        e.Router.Pre(middleware.Rewrite(map[string]string{
          "/_":  "/",
          "/_*": "/",
        }))
        log.Default().Println("PocketBase UI is disabled")
      }
      e.Router.GET("/*", apis.StaticDirectoryHandler(os.DirFS(publicDir), indexFallback))
      return nil
    })
  }

  func getenvBool(key string) bool {
    val := os.Getenv(key)
    ret, err := strconv.ParseBool(val)
    if err != nil {
      return false
    }
    return ret
  }
  ```

</details>

<details>
  <summary>docker-compose.yml</summary>

  ```yml
  version: "3"

  pocketbase-vue-starter:
    image: ghcr.io/mrsessions/pocketbase-vue-starter:latest
    container_name: pocketbase-vue-starter
    restart: unless-stopped
    environment:
      - POCKETBASE_DISABLE_UI=false # Set to true to disable PocketBase UI
    volumes:
      - ./pocketbase:/data
    ports:
      - 8090:8090

  volumes:
    pocketbase-vue-starter:
  ```
</details>

<details>
  <summary>Dockerfile (Build Final Image Section)</summary>

  ```dockerfile
  # build final image
  FROM golang:1.20.0-alpine3.17 AS final

  WORKDIR /app

  COPY --from=builder /app/pocketbase ./

  COPY --from=node-builder /app/dist ./dist

  # Set to true to disable the PocketBase UI if not using Docker Compose
  ENV POCKETBASE_DISABLE_UI=false

  EXPOSE 8090

  RUN ls /app

  CMD ["/app/pocketbase", "serve", "--http=0.0.0.0:8090"]
  ```

</details>
