### ISSUE TITLE
Why Vuetify?

### ISSUE THREAD

**Issue by mbnoimi** [MRSessions/pocketbase-vue-starter#15]
I'm just a curious why you pick to use Vuetify?

It missing some important components by comparing to Quasar

**Comment by MRSessions** [comment]
Valid question @mbnoimi. While you make a valid point about the state of Vuetify 3, I think it's still a solid UI library to use. You aren't limited to only using Vuetify if you were to pull off this template. Personally, I do like Vuetify and it was one of the first UI libraries I learned when I learned Vue.

With that said, I have played around with other UI libraries and thought about making additional template projects, but I have unfortunately been swamped with work the past few weeks.

If you'd like to see something else like using it Quasar, I'm more than happy to do that if you'd like. Otherwise feel free to create a template project yourself with the same ideas or different to what I have here. If you do create one, definitely share it and I will link to that project template, if you'd like and would also do the same with mine.
